name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    # display some information that
    #can be accessed during workflow run
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"

